#!/bin/sh

docker run -ti \
                --publish 445:445 \
                --publish 139:139 \
                --volume ${1:-`pwd`}:/srv \
				--env workgroup=${2:-workgroup} \
                modemman/samba-dancer
